version: '2'
services:
  zookeeper:
    image: myimagestore/zookeeper
    ports:
      - "2181:2181"
    kafka:
      image: myimagestore/kafka
      ports:
        - "9092:9092"
        enviroment:
          KAFKA_ADVERTISED_HOST_NAME: 127.0.0.1
          KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
          KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'false'